


/* BASE DE DATOS ETT

CREATE DATABASE ETT;

Nos conectamos a la base de datos
\c ett
*/

CREATE TABLE PERSONA( DNI CHAR(9) CONSTRAINT PERSONA_DNI_PK PRIMARY KEY,
NOM_PERSONA VARCHAR(15) CONSTRAINT PERSONA_NOM_PERSONA_NN NOT NULL,
ESTUDIOS VARCHAR(120),
PROF_DESEADA 
);