


/* BASE DE DATOS ETT

CREATE DATABASE ETT;

Nos conectamos a la base de datos
\c ett
*/

CREATE TABLE PERSONA( 
    DNI CHAR(9) CONSTRAINT PERSONA_DNI_PK PRIMARY KEY,
    NOM VARCHAR(15) CONSTRAINT PERSONA_NOM_NN NOT NULL,
    ESTUDIOS VARCHAR(120),
    PROF_DESEADA VARCHAR(20)
);

CREATE TABLE PUESTO(
    ID VARCHAR(3) CONSTRAINT PUESTO_ID_PK PRIMARY KEY,
    PROF_SOLICIT VARCHAR(20) CONSTRAINT PUESTO_PROF_SOLICIT_NN NOT NULL,
    LUGAR_TRAB VARCHAR(20) CONSTRAINT PUESTO_LUGAR_TRAB_NN NOT NULL,
    COND_EXIGIDA VARCHAR(30)
);

CREATE TABLE EMPRESA(
    CIF CHAR(9) CONSTRAINT EMPRESA_CIF_PK PRIMARY KEY,
    NOM VARCHAR(20) CONSTRAINT EMPRESA_NOM_UK UNIQUE,
    SECTOR VARCHAR(20) CONSTRAINT EMPRESA_SECTOR_NN NOT NULL,
    TIPUS VARCHAR(14) CONSTRAINT EMPRESA_TIPUS_CK CHECK (TIPUS IN ('multinacional', 'pymes')),
    CIUDAD_UBICADA VARCHAR(20),
    NUM_PAISES SMALLINT
);

CREATE TABLE ENTREVISTA(
    PUESTO VARCHAR(3),
    DNI CHAR(9),
    AVALUACIO SMALLINT,
    CONSTRAINT ENTREVISTA_PUESTODNI_PK PRIMARY KEY(PUESTO, DNI),
    CONSTRAINT ENTREVISTA_PUESTO_FK FOREIGN KEY (PUESTO) REFERENCES PUESTO(ID)
    ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ENTREVISTA_DNI_FK FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CONTRACTE(
    DATA_INICI DATE,
    CIF CHAR(9),
    DNI CHAR(9),
    DURADA NUMERIC,
    SOU MONEY,
    CONSTRAINT CONTRACTE_DATADNI_PK PRIMARY KEY(DATA_INICI, DNI),
    CONSTRAINT CONTRACTE_CIF_FK FOREIGN KEY (CIF) REFERENCES EMPRESA(CIF)
    ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT CONTRACTE_DNI_FK FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
    ON UPDATE CASCADE ON DELETE CASCADE
);