


/* BASE DE DATOS GABINET

CREATE DATABASE GABINET;

Nos conectamos a la base de datos
\c gabinet
*/

CREATE TABLE CLIENT( 
    DNI CHAR(9) CONSTRAINT CLIENT_DNI_PK PRIMARY KEY,
    NOM VARCHAR(20) CONSTRAINT CLIENT_NOM_NN NOT NULL,
    ADRECA VARCHAR(40),
    TELEFON VARCHAR(13)
);


CREATE TABLE PROCURADOR( 
    DNI CHAR(9) CONSTRAINT PROCURADOR_DNI_PK PRIMARY KEY,
    NOM VARCHAR(20) CONSTRAINT PROCURADOR_NOM_NN NOT NULL,
    ADRECA VARCHAR(40),
    TELEFON VARCHAR(13)
);

CREATE TABLE ASSUMPTE(
    NUMEXPEDIENT VARCHAR(3) CONSTRAINT ASSUMPTE_NUMEXPEDIENT_PK PRIMARY KEY,
    DESCRIPCIO VARCHAR(120),
    DATAINI DATE CONSTRAINT ASSUMPTE_DATAINI_NN NOT NULL,
    DATAARXIU DATE,
    ESTAT CHAR(1) CONSTRAINT ASSUMPTE_ESTAT_CK CHECK (ESTAT IN ('O', 'T'))

);