
/*
CREATE DATABASE scott;
\c scott
*/

--Tabla DEPT
CREATE TABLE DEPT(DEPTNO smallint CONSTRAINT DEPT_DEPTNO_PK PRIMARY KEY,  
DNAME varchar(14) CONSTRAINT DEPT_DNAME_UK UNIQUE,
LOC varchar(13) CONSTRAINT DEPT_LOC_NN NOT NULL);

--Tabla EMP
CREATE TABLE EMP
(EMPNO smallint CONSTRAINT EMP_EMPNO_PK PRIMARY KEY,
ENAME varchar(10) CONSTRAINT EMP_ENAME_UK UNIQUE,
JOB varchar(9) CONSTRAINT EMP_JOB_NN NOT NULL,
MGR smallint,
HIREDATE DATE default now(),
SAL numeric(8, 2),
COMM decimal(8, 2),
DEPTNO smallint,
CONSTRAINT EMP_DEPTNO_FK FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO),
CONSTRAINT EMP_MGR_FK FOREIGN KEY (MGR) REFERENCES EMP (EMPNO));

--Tabla SALGRADE
CREATE TABLE SALGRADE (GRADE smallint CONSTRAINT SALGRADE_GRADE_PK PRIMARY KEY,
LOSAL numeric(8, 2),
HISAL numeric(8, 2));